Vagrant.configure("2") do |config|
  config.vm.box = "marcinbojko/ubuntu2204_arm64"  # ARM64 + VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end